[package]
name = "kore"
version = "0.1.0"
authors = ["luzzif <federico.luzzi@mondora.com>"]

[dependencies]
volatile = "0.2.3"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.4.6"

[package.metadata.bootimage]
default-target = "target.json"
